

 export const bodyFrames = [
  "/images/shapes/body-frames/body-1.webp",
  "/images/shapes/body-frames/body-2.webp",
  "/images/shapes/body-frames/body-3.webp",
  "/images/shapes/body-frames/body-4.webp",
  "/images/shapes/body-frames/body-5.webp",
  "/images/shapes/body-frames/body-6.webp",
  "/images/shapes/body-frames/body-7.webp",
  "/images/shapes/body-frames/body-8.webp",
  "/images/shapes/body-frames/body-9.webp",
  "/images/shapes/body-frames/body-10.webp",
  "/images/shapes/body-frames/body-11.webp",
  "/images/shapes/body-frames/body-12.webp",
  "/images/shapes/body-frames/body-13.webp",
  "/images/shapes/body-frames/body-14.webp",
  "/images/shapes/body-frames/body-15.webp",
  "/images/shapes/body-frames/body-16.webp",
  "/images/shapes/body-frames/body-17.webp",
  "/images/shapes/body-frames/body-18.webp",
  "/images/shapes/body-frames/body-19.webp",
  "/images/shapes/body-frames/body-20.webp",
  "/images/shapes/body-frames/body-21.webp",
  "/images/shapes/body-frames/body-22.webp",
  "/images/shapes/body-frames/body-23.webp",
  "/images/shapes/body-frames/body-24.webp",
];

  export const eyeFrames = [
    "/images/shapes/eye-frames/eye-frame-1.svg",
    "/images/shapes/eye-frames/eye-frame-2.svg",
    "/images/shapes/eye-frames/eye-frame-3.svg",
    "/images/shapes/eye-frames/eye-frame-4.svg",
    "/images/shapes/eye-frames/eye-frame-5.svg",
     "/images/shapes/eye-frames/eye-frame-6.svg",
    "/images/shapes/eye-frames/eye-frame-7.svg",
    "/images/shapes/eye-frames/eye-frame-8.svg",
    "/images/shapes/eye-frames/eye-frame-9.svg",
    "/images/shapes/eye-frames/eye-frame-10.svg",
  ];
 export const eyeBalls = [
  "/images/shapes/eye-balls/eye-ball-1.svg",
  "/images/shapes/eye-balls/eye-ball-2.svg",
  "/images/shapes/eye-balls/eye-ball-3.svg",
  "/images/shapes/eye-balls/eye-ball-4.svg",
  "/images/shapes/eye-balls/eye-ball-5.svg",
  "/images/shapes/eye-balls/eye-ball-6.svg",
  "/images/shapes/eye-balls/eye-ball-7.svg",
  "/images/shapes/eye-balls/eye-ball-8.svg",
  "/images/shapes/eye-balls/eye-ball-9.svg",
  "/images/shapes/eye-balls/eye-ball-10.svg",
  "/images/shapes/eye-balls/eye-ball-11.svg",
  "/images/shapes/eye-balls/eye-ball-12.svg",
  "/images/shapes/eye-balls/eye-ball-13.svg",
  "/images/shapes/eye-balls/eye-ball-14.svg",
  "/images/shapes/eye-balls/eye-ball-15.svg",
  "/images/shapes/eye-balls/eye-ball-16.svg",
  "/images/shapes/eye-balls/eye-ball-17.svg",
  "/images/shapes/eye-balls/eye-ball-18.svg",
  "/images/shapes/eye-balls/eye-ball-19.svg",
  "/images/shapes/eye-balls/eye-ball-20.svg",
  "/images/shapes/eye-balls/eye-ball-21.svg",

];
