export const logos = [
  "/images/logos/drive.webp",
  "/images/logos/fb.webp",
  // "/images/logos/game.webp",
  "/images/logos/google.webp",
  "/images/logos/insta.webp",
  "/images/logos/mail.webp",
  "/images/logos/map.webp",
  "/images/logos/meet.webp",
  // "/images/logos/p.webp",
  "/images/logos/skype.webp",
  "/images/logos/snap.webp",
  "/images/logos/teams.webp",
  "/images/logos/telegram.webp",
  "/images/logos/whatsupp.webp",
  "/images/logos/yt.webp",
  "/images/logos/zoom.webp",
  "/images/logos/pin.webp",
  "/images/logos/chatgpt.webp",
  "/images/logos/x.webp",
  // "/images/logos/zm-logo.webp",
];
