export const logos = [
  "/images/logos/drive.webp",
  "/images/logos/fb.webp",
   "/images/logos/telegram.webp",
  "/images/logos/google.webp",
   "/images/logos/insta.webp",
   "/images/logos/gmail.webp",
  "/images/logos/map.webp",
   "/images/logos/g-meet.webp",
   "/images/logos/snap.webp",
   "/images/logos/skype.webp",
  // "/images/logos/snaps.webp",
   "/images/logos/teams.webp",
  // "/images/logos/telegram.webp",
   "/images/logos/whatsup.webp",
   "/images/logos/yt.webp",
   "/images/logos/zoom.webp",
   "/images/logos/pin.webp",
   "/images/logos/chatgpt.webp",
   "/images/logos/x.webp",
  // "/images/logos/zm-logo.webp",
];
