import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext"; // 👈 Import your provider

export const metadata = {
  title: "Zm QR Code Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider> {/* 👈 Wrap the app in provider */}
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
