// src/app/layout.jsx
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import ScrollToTop from "@/components/scrollToTop/scrollToTop";
import { LanguageProvider } from "@/context/languageContext/LanguageContext";
import DesignProvider from "@/context/qrCodeDesignContext/DesignProvider";
import ServicesProvider from "@/context/servicesContext/SercivesProvider";
import ReduxProvider from "@/redux/reduxProvider/reduxProvider";

// ✅ Start cron job only on server
if (typeof window === "undefined") {
  import("@/lib/startCron").then(({ default: initCron }) => initCron());
}

export const metadata = {
  title: "Zm QR Code Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            duration: 5000,
            style: {
              fontSize: "18px",
              padding: "12px 16px",
              maxWidth: "500px",
              wordBreak: "break-word",
              whiteSpace: "pre-wrap",
            },
          }}
        />
        <ReduxProvider>
          <LanguageProvider>
              <ServicesProvider>
                <DesignProvider>
                  <ScrollToTop />
                  {children}
                </DesignProvider>
              </ServicesProvider>
          </LanguageProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
