import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import "./globals.css";
import { LanguageProvider } from "@/context/languageContext/LanguageContext"; // 👈 Import your provider
import DesignProvider from "@/context/qrCodeDesignContext/DesignProvider";
import ServicesProvider from "@/context/servicesContext/ServivesProvider";


export const metadata = {
  title: "Zm QR Code Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider> {/* 👈 Wrap the app in provider */}
          <ServicesProvider>
          <DesignProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
          </DesignProvider>
          </ServicesProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
