// export const stickers = [
//   '/images/stickers/stickers-1.svg',
//   '/images/stickers/stickers-2.svg',
//   '/images/stickers/stickers-3.svg',
//   '/images/stickers/stickers-4.svg',
//   '/images/stickers/stickers-5.svg',
//   '/images/stickers/stickers-6.svg',
//   '/images/stickers/stickers-7.svg',
//   '/images/stickers/stickers-8.svg',
//   '/images/stickers/stickers-9.svg',
//   '/images/stickers/stickers-10.svg',
//   '/images/stickers/stickers-11.svg',
//   '/images/stickers/stickers-12.svg',
//   '/images/stickers/stickers-13.svg',
//   '/images/stickers/stickers-14.svg',
//   '/images/stickers/stickers-15.svg',
//   '/images/stickers/stickers-16.svg',
//   '/images/stickers/stickers-17.svg',
//   '/images/stickers/stickers-18.svg',
//   '/images/stickers/stickers-19.svg',
//   '/images/stickers/stickers-20.svg',
//   '/images/stickers/stickers-21.svg',
//   '/images/stickers/stickers-22.svg',
//   '/images/stickers/stickers-23.svg',
//   '/images/stickers/stickers-24.svg',
//   '/images/stickers/stickers-25.svg',
//   '/images/stickers/stickers-26.svg',
//   '/images/stickers/stickers-27.svg',
//   '/images/stickers/stickers-28.svg',
//   '/images/stickers/stickers-29.svg',
//   '/images/stickers/stickers-30.svg',
//   '/images/stickers/stickers-31.svg',
//   '/images/stickers/stickers-32.svg',
//   '/images/stickers/stickers-33.svg',
//   '/images/stickers/stickers-34.svg',
//   '/images/stickers/stickers-35.svg',
//   '/images/stickers/stickers-36.svg',
//   '/images/stickers/stickers-37.svg',
//   '/images/stickers/stickers-38.svg',
//   '/images/stickers/stickers-39.svg',
//   '/images/stickers/stickers-40.svg',
//   '/images/stickers/stickers-41.svg',
//   '/images/stickers/stickers-42.svg',
//   '/images/stickers/stickers-43.svg',
//   '/images/stickers/stickers-44.svg',
//   '/images/stickers/stickers-45.svg',
//   '/images/stickers/stickers-46.svg',
//   '/images/stickers/stickers-47.svg',
//   '/images/stickers/stickers-48.svg',
//   '/images/stickers/stickers-49.svg',
//   '/images/stickers/stickers-50.svg',
//   '/images/stickers/stickers-51.svg',
//   '/images/stickers/stickers-52.svg',
//   '/images/stickers/stickers-53.svg',
//   '/images/stickers/stickers-54.svg',
//   '/images/stickers/stickers-55.svg',
//   '/images/stickers/stickers-56.svg',
//   '/images/stickers/stickers-57.svg',
//   '/images/stickers/stickers-58.svg',
//   '/images/stickers/stickers-59.svg',
//   '/images/stickers/stickers-60.svg',
//   '/images/stickers/stickers-61.svg',
//   '/images/stickers/stickers-62.svg',
//   '/images/stickers/stickers-63.svg',
//   '/images/stickers/stickers-64.svg',
//   '/images/stickers/stickers-65.svg',
//   '/images/stickers/stickers-66.svg',
//   '/images/stickers/stickers-67.svg',
//   '/images/stickers/stickers-68.svg',
//   '/images/stickers/stickers-69.svg',
//   '/images/stickers/stickers-70.svg',
//   '/images/stickers/stickers-71.svg',
//   '/images/stickers/stickers-72.svg',
//   '/images/stickers/stickers-73.svg',
//   '/images/stickers/stickers-74.svg',
//   '/images/stickers/stickers-75.svg',
//   '/images/stickers/stickers-76.svg',
//   '/images/stickers/stickers-77.svg',
//   '/images/stickers/stickers-78.svg',
//   '/images/stickers/stickers-79.svg',
//   '/images/stickers/stickers-80.svg',
//   '/images/stickers/stickers-81.svg',
//   '/images/stickers/stickers-82.svg',
//   '/images/stickers/stickers-83.svg',
//   '/images/stickers/stickers-84.svg',
//   '/images/stickers/stickers-85.svg',
//   '/images/stickers/stickers-86.svg',
//   '/images/stickers/stickers-87.svg',
//   '/images/stickers/stickers-88.svg',
//   '/images/stickers/stickers-89.svg',
//   '/images/stickers/stickers-90.svg',
//   '/images/stickers/stickers-91.svg',
//   '/images/stickers/stickers-92.svg',
//   '/images/stickers/stickers-93.webp',
//   '/images/stickers/stickers-94.webp',
//   '/images/stickers/stickers-95.webp',
//   '/images/stickers/stickers-96.webp',
//   '/images/stickers/stickers-97.webp',
//   '/images/stickers/stickers-98.webp',
//   '/images/stickers/stickers-99.webp',
//   '/images/stickers/stickers-100.webp',
//   '/images/stickers/stickers-101.webp',
//   '/images/stickers/stickers-102.webp',
//   '/images/stickers/stickers-103.webp',
//   '/images/stickers/stickers-104.webp',
//   '/images/stickers/stickers-106.svg',
//   '/images/stickers/stickers-107.svg',
//   '/images/stickers/stickers-108.svg',
//   '/images/stickers/stickers-109.svg',
//   '/images/stickers/stickers-110.svg',
//   '/images/stickers/stickers-111.svg',
//   '/images/stickers/stickers-112.webp',
//   '/images/stickers/stickers-113.webp',
//   '/images/stickers/stickers-114.webp',
//   '/images/stickers/stickers-115.webp',
//   '/images/stickers/stickers-116.webp',
//   '/images/stickers/stickers-117.webp',
//   '/images/stickers/stickers-118.webp',
//   '/images/stickers/stickers-119.webp',
//   '/images/stickers/stickers-120.webp',
//   '/images/stickers/stickers-121.webp',
//   '/images/stickers/stickers-122.webp',
//   '/images/stickers/stickers-123.svg',
//   '/images/stickers/stickers-124.svg',
//   '/images/stickers/stickers-125.webp',
// ];


export const stickerConfig = {
  "/images/stickers/a.png": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/b.png": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/c.png": {
    qrTop: "45%",
    qrLeft: "50%",
    scale: 150,
    logoTop: "48%",
    logoLeft: "51%",
    logoSize: 35,
  },
  "/images/stickers/d.webp": {
    qrTop: "40%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "43%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/e.png": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  //  "/images/stickers/f.webp": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 180,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/g.jpg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/h.webp": {
    qrTop: "45%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "45%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/i.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/j.webp": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 180,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  //  "/images/stickers/k.webp": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 180,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-1.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-2.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-3.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-4.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-5.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-6.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-7.svg": {
    qrTop: "55%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "55%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-8.svg": {
    qrTop: "64%",
    qrLeft: "55%",
    scale: 150,
    logoTop: "65%",
    logoLeft: "55%",
    logoSize: 35,
  },
  "/images/stickers/stickers-9.svg": {
    qrTop: "67%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "67%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-10.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 180,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-11.svg": {
    qrTop: "42%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "44%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-12.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-13.svg": {
    qrTop: "67%",
    qrLeft: "50%",
    scale: 150,
    logoTop: "66%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-14.svg": {
    qrTop: "65%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "63%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-15.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-16.svg": {
    qrTop: "75%",
    qrLeft: "50%",
    scale: 120,
    logoTop: "75%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-17.svg": {
    qrTop: "65%",
    qrLeft: "64%",
    scale: 160,
    logoTop: "64%",
    logoLeft: "65%",
    logoSize: 35,
  },
  "/images/stickers/stickers-18.png": {
    qrTop: "70%",
    qrLeft: "50%",
    scale: 120,
    logoTop: "70%",
    logoLeft: "50%",
    logoSize: 35,
  },
//   "/images/stickers/stickers-19.png": {
//     qrTop: "50%",
//     qrLeft: "38%",
//     scale: 120,
//     logoTop: "50%",
//     logoLeft: "38%",
//     logoSize: 32,
//   },

  "/images/stickers/stickers-20.jpg": {
    qrTop: "62%",
    qrLeft: "40%",
    scale: 250,
    logoTop: "60%",
    logoLeft: "40%",
    logoSize: 30,
  },
  "/images/stickers/stickers-21.png": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-22.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-23.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-24.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-25.svg": {
    qrTop: "68%",
    qrLeft: "50%",
    scale: 150,
    logoTop: "68%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-26.png": {
    qrTop: "55%",
    qrLeft: "42%",
    scale: 160,
    logoTop: "55%",
    logoLeft: "42%",
    logoSize: 35,
  },
  "/images/stickers/stickers-27.png": {
    qrTop: "45%",
    qrLeft: "50%",
    scale: 200,
    logoTop: "45%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-28.png": {
    qrTop: "55%",
    qrLeft: "53%",
    scale: 160,
    logoTop: "57%",
    logoLeft: "53%",
    logoSize: 35,
  },
  "/images/stickers/stickers-29.png": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-30.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-31.svg": {
    qrTop: "58%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-32.svg": {
    qrTop: "55%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "57%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-33.svg": {
    qrTop: "66%",
    qrLeft: "47%",
    scale: 160,
    logoTop: "68%",
    logoLeft: "48%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-34.svg": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  "/images/stickers/stickers-35.svg": {
    qrTop: "62%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "62%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-36.svg": {
    qrTop: "40%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "42%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-37.svg": {
    qrTop: "55%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "55%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-38.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-39.svg": {
    qrTop: "40%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "42%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-40.svg": {
  //   qrTop: "40%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "42%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-41.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-42.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-43.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-44.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-45.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-46.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-47.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-48.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-49.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-50.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-51.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-52.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-53.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-54.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-55.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-56.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-57.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-58.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-59.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-60.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-61.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-62.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-63.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-64.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-65.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-66.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-67.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-68.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-69.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-70.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-71.svg": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-72.svg": {
    qrTop: "65%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-73.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-74.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-75.svg": {
  //   qrTop: "58%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-76.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-77.svg": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-78.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-79.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-80.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-81.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-82.svg": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-83.svg": {
    qrTop: "65%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-84.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-85.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-86.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-87.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-88.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-89.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-90.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-91.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-92.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-93.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-94.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  "/images/stickers/stickers-95.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-96.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-97.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-98.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-99.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-100.webp": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  "/images/stickers/stickers-101.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-102.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-103.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-104.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-105.svg": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  "/images/stickers/stickers-106.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-107.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-108.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-109.svg": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-110.svg": {
    qrTop: "40%",
    qrLeft: "50%",
    scale: 200,
    logoTop: "40%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-111.svg": {
    qrTop: "62%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "62%",
    logoLeft: "50%",
    logoSize: 35,
  },
  // "/images/stickers/stickers-112.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-113.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-114.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-115.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-116.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-117.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-118.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-119.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  // "/images/stickers/stickers-120.webp": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  // "/images/stickers/stickers-121.webp": {
  //   qrTop: "50%",
  //   qrLeft: "50%",
  //   scale: 160,
  //   logoTop: "50%",
  //   logoLeft: "50%",
  //   logoSize: 35,
  // },
  // "/images/stickers/stickers-122.webp": { qrTop: "50%", qrLeft: "50%", scale: 160, logoTop: "50%", logoLeft: "50%", logoSize: 35 },
  "/images/stickers/stickers-123.svg": {
    qrTop: "55%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "58%",
    logoLeft: "50%",
    logoSize: 35,
  },
  "/images/stickers/stickers-124.svg": {
    qrTop: "55%",
    qrLeft: "50%",
    scale: 160,
    logoTop: "58%",
    logoLeft: "50%",
    logoSize: 35,
  },
//   "/images/stickers/stickers-125.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 160,
//     logoTop: "50%",
//     logoLeft: "50%",
//     logoSize: 35,
//   },

};
