export const qrShapeConfig = {
  "/images/qr-shapes/clouds.png": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 0.6,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/traingle.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/mirror.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/cat with mustach.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/oct.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/cloud.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/hat.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
   "/images/qr-shapes/ice cream in cone.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/spider.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/circle.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.2,
    logoTop: "50%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/bottle.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/cat.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/cup.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/lovesymbol.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/flower.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/pine.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/rabbit.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/shirt.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/ice.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/tree.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/lotus.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/frock.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "70%",
    logoLeft: "30%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/palm.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/guitar.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/fish.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/glass.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/laptop.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/gift.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
 
  "/images/qr-shapes/like.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/umbrella.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/waterdrop.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/goun.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/apple.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/mango.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/house.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/biryani.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/lock.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/boxing gloves.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/moon-star.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/dou .webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/handbag.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/bike.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/tv.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/cap.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/cooldrink.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/coco.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/auto.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
  "/images/qr-shapes/car.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
    logoTop: "65%",
    logoLeft: "50%",
    logoSize: {
      default: 22,
      tablet: 20,
      mobile: 20,
    },
  },
};
// export const qrShapeConfig = {
//   "/images/qr-shapes/circle.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.2,
//   },
//   "/images/qr-shapes/bottle.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/cat.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/cup.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/lovesymbol.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/flower.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/pine.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/rabbit.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/shirt.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/ice.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/tree.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/lotus.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/oct.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/cloud.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/frock.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/palm.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/guitar.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/fish.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/glass.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/laptop.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/cat with mustach.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/gift.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/ice cream in cone.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/like.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/umbrella.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/waterdrop.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/goun.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/traingle.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/apple.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/mango.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/hat.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/house.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/biryani.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/lock.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/spider.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/boxing gloves.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/moon-star.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/dou .png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/handbag.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/mirror.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/bike.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/tv.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/cap.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/cooldrink.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/coco.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/auto.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/car.png": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//   },
//   "/images/qr-shapes/heart.png": { // Added from your example
//     qrTop: "48%",
//     qrLeft: "49%",
//     scale: 1.1,
//   },
// };

// export const images = [
//   "/images/qr-shapes/circle.png",
//   "/images/qr-shapes/bottle.png",
//   "/images/qr-shapes/cat.png",
//   "/images/qr-shapes/cup.png",
//   "/images/qr-shapes/lovesymbol.png",
//   "/images/qr-shapes/flower.png",
//   "/images/qr-shapes/pine.png",
//   "/images/qr-shapes/rabbit.png",
//   "/images/qr-shapes/shirt.png",
//   "/images/qr-shapes/ice.png",
//   "/images/qr-shapes/tree.png",
//   "/images/qr-shapes/lotus.png",
//   "/images/qr-shapes/oct.png",
//   "/images/qr-shapes/cloud.png",
//   "/images/qr-shapes/frock.png",
//   "/images/qr-shapes/palm.png",
//   "/images/qr-shapes/guitar.png",
//   "/images/qr-shapes/fish.png",
//   "/images/qr-shapes/glass.png",
//   "/images/qr-shapes/laptop.png",
//   "/images/qr-shapes/cat with mustach.png",
//   "/images/qr-shapes/gift.png",
//   "/images/qr-shapes/ice cream in cone.png",
//   "/images/qr-shapes/like.png",
//   "/images/qr-shapes/umbrella.png",
//   "/images/qr-shapes/waterdrop.png",
//   "/images/qr-shapes/goun.png",
//   "/images/qr-shapes/traingle.png",
//   "/images/qr-shapes/apple.png",
//   "/images/qr-shapes/mango.png",
//   "/images/qr-shapes/hat.png",
//   "/images/qr-shapes/house.png",
//   "/images/qr-shapes/biryani.png",
//   "/images/qr-shapes/lock.png",
//   "/images/qr-shapes/spider.png",
//   "/images/qr-shapes/boxing gloves.png",
//   "/images/qr-shapes/moon-star.png",
//   "/images/qr-shapes/dou .png",
//   "/images/qr-shapes/handbag.png",
//   "/images/qr-shapes/mirror.png",
//   "/images/qr-shapes/bike.png",
//   "/images/qr-shapes/tv.png",
//   "/images/qr-shapes/cap.png",
//   "/images/qr-shapes/cooldrink.png",
//   "/images/qr-shapes/coco.png",
//   "/images/qr-shapes/auto.png",
//   "/images/qr-shapes/car.png",
// ];
