// export const qrShapeConfig = {
//   // "/images/qr-shapes/cloud-1.webp": {
//   //   qrTop: "50%",
//   //   qrLeft: "50%",
//   //   scale: 0.6,
//   //   logoTop: "50%",
//   //   logoLeft: "50%",
//   //   logoSize: {
//   //     default: 22,
//   //     tablet: 20,
//   //     mobile: 20,
//   //   },
//   // },
//   "/images/qr-shapes/traingle.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/mirror.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/cat with mustach.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/oct.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/cloud.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/hat.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//    "/images/qr-shapes/ice cream in cone.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/spider.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/circle.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.2,
//     logoTop: "50%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/bottle.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/cat.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/cup.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/lovesymbol.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/flower.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/pine.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/rabbit.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/shirt.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/ice.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/tree.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/lotus.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/frock.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "70%",
//     logoLeft: "30%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/palm.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/guitar.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/fish.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/glass.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/laptop.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/gift.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
 
//   "/images/qr-shapes/like.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/umbrella.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/waterdrop.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/goun.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/apple.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/mango.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/house.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/biryani.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/lock.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/boxing gloves.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/moon-star.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/dou .webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/handbag.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/bike.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/tv.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/cap.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/cooldrink.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/coco.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/auto.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
//   "/images/qr-shapes/car.webp": {
//     qrTop: "50%",
//     qrLeft: "50%",
//     scale: 1.0,
//     logoTop: "65%",
//     logoLeft: "50%",
//     logoSize: {
//       default: 22,
//       tablet: 20,
//       mobile: 20,
//     },
//   },
// };

export const qrShapeConfig = {
     "/images/qr-shapes/cloud-1.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 0.6
  },
  "/images/qr-shapes/traingle.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/mirror.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/cat with mustach.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/oct.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/cloud.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/hat.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/ice cream in cone.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/spider.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/circle.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.2,
  },
  "/images/qr-shapes/bottle.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/cat.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/cup.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/lovesymbol.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/flower.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/pine.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/rabbit.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/shirt.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/ice.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/tree.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/lotus.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/frock.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/palm.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/guitar.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/fish.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/glass.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/laptop.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/gift.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/like.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/umbrella.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/waterdrop.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/goun.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/apple.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/mango.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/house.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/biryani.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/lock.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/boxing gloves.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/moon-star.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/dou .webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/handbag.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/bike.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/tv.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/cap.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/cooldrink.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/coco.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/auto.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
  "/images/qr-shapes/car.webp": {
    qrTop: "50%",
    qrLeft: "50%",
    scale: 1.0,
  },
};





// export const qrShapeConfig = [
//   "/images/qr-shapes/traingle.webp",
//   "/images/qr-shapes/mirror.webp",
//   "/images/qr-shapes/cat with mustach.webp",
//   "/images/qr-shapes/oct.webp",
//   "/images/qr-shapes/cloud.webp",
//   "/images/qr-shapes/hat.webp",
//   "/images/qr-shapes/ice cream in cone.webp",
//   "/images/qr-shapes/spider.webp",
//   "/images/qr-shapes/circle.webp",
//   "/images/qr-shapes/bottle.webp",
//   "/images/qr-shapes/cat.webp",
//   "/images/qr-shapes/cup.webp",
//   "/images/qr-shapes/lovesymbol.webp",
//   "/images/qr-shapes/flower.webp",
//   "/images/qr-shapes/pine.webp",
//   "/images/qr-shapes/rabbit.webp",
//   "/images/qr-shapes/shirt.webp",
//   "/images/qr-shapes/ice.webp",
//   "/images/qr-shapes/tree.webp",
//   "/images/qr-shapes/lotus.webp",
//   "/images/qr-shapes/frock.webp",
//   "/images/qr-shapes/palm.webp",
//   "/images/qr-shapes/guitar.webp",
//   "/images/qr-shapes/fish.webp",
//   "/images/qr-shapes/glass.webp",
//   "/images/qr-shapes/laptop.webp",
//   "/images/qr-shapes/gift.webp",
//   "/images/qr-shapes/like.webp",
//   "/images/qr-shapes/umbrella.webp",
//   "/images/qr-shapes/waterdrop.webp",
//   "/images/qr-shapes/goun.webp",
//   "/images/qr-shapes/apple.webp",
//   "/images/qr-shapes/mango.webp",
//   "/images/qr-shapes/house.webp",
//   "/images/qr-shapes/biryani.webp",
//   "/images/qr-shapes/lock.webp",
//   "/images/qr-shapes/boxing gloves.webp",
//   "/images/qr-shapes/moon-star.webp",
//   "/images/qr-shapes/dou .webp",
//   "/images/qr-shapes/handbag.webp",
//   "/images/qr-shapes/bike.webp",
//   "/images/qr-shapes/tv.webp",
//   "/images/qr-shapes/cap.webp",
//   "/images/qr-shapes/cooldrink.webp",
//   "/images/qr-shapes/coco.webp",
//   "/images/qr-shapes/auto.webp",
//   "/images/qr-shapes/car.webp",
// ];